#!/usr/bin/env bash
# Install lunus.sf -- differentiable structure factors and diffuse scattering --
# into the active environment, from its own repository.
#
# lunus is developed at github.com/lanl/lunus, and is deliberately not vendored
# into this repo nor synced to pods (see .actlignore).
#
# You do NOT normally need this script. lunus IS declared in pyproject.toml and
# resolved in pixi.lock, so every pixi environment already has it at the pinned
# tag. This is for the one case the lock cannot cover: testing a lunus commit
# NEWER than the pin without regenerating the lock.
#
# That matters because the lock can only be regenerated by the Relock workflow,
# never locally -- `pixi lock` is all-or-nothing, with no --environment or
# --platform selector, and solving linux-64 needs a linux-64 prefix. So the edit
# -> test loop on lunus itself would otherwise cost a CI round trip per commit.
# The cause is sdist-only transitive deps (ihm has no wheel at any version), not
# anything about how lunus itself is distributed.
#
# Publishing lunus to PyPI would NOT retire this script. It would only make
# moving to a RELEASED version an ordinary dependency bump; testing a commit
# that has not been released yet still has to go around pixi exactly like this.
#
# It is a thin wrapper over one pip call. What it adds is worth having:
#   - the ref comes from pyproject.toml, so it cannot drift from the pin
#   - --no-deps, without which --force-reinstall pulls torch and gemmi from
#     PyPI over the conda-forge builds pixi installed
#   - an import check of the actual symbols, because lunus.sf resolves its API
#     lazily (PEP 562), so a bare `import lunus.sf` passes even when broken
#
# Usage (from the repo root, inside the environment you want it in):
#   pixi run -e boltz bash scripts/install_lunus.sh              # reinstall the pin
#   LUNUS_REF=sf pixi run -e boltz bash scripts/install_lunus.sh # branch tip
set -euo pipefail

LUNUS_REPO="${LUNUS_REPO:-https://github.com/lanl/lunus.git}"
# Read straight out of pyproject.toml so an unqualified run cannot diverge from
# the locked environment. Not duplicated here on purpose: the previous hardcoded
# copy went stale the moment the pin moved to a tag. Pass LUNUS_REF to install
# something else.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LUNUS_REF="${LUNUS_REF:-$(sed -n 's/^lunus = {tag = "\([^"]*\)".*/\1/p' "${HERE}/../pyproject.toml")}"
if [ -z "${LUNUS_REF}" ]; then
  echo "Could not read the lunus tag from pyproject.toml; pass LUNUS_REF explicitly." >&2
  exit 1
fi

echo "Installing lunus[sf] from ${LUNUS_REPO}@${LUNUS_REF}"

# --force-reinstall because pip skips a reinstall when the version string is
# unchanged, which is the normal case for a newer commit still calling itself
# 0.2.0 -- the very thing this script exists to test.
#
# --no-deps is not optional alongside it. --force-reinstall means "reinstall ALL
# packages", dependencies included, so without it pip would pull torch and gemmi
# from PyPI over the conda-forge builds pixi installed. The `sf` extra is kept
# for documentation; under --no-deps it resolves nothing. Both are already in
# every environment, and the import check below fails loudly if they are not.
python -m pip install --force-reinstall --no-deps "lunus[sf] @ git+${LUNUS_REPO}@${LUNUS_REF}"

# Verify rather than trust the exit status. lunus.sf resolves its public API
# lazily (PEP 562), so `import lunus.sf` alone succeeds even when the torch-side
# modules are broken or absent -- name the symbols the diffuse reward needs.
python - <<'PY'
from importlib.metadata import version

from lunus.sf import mean_and_diffuse, structure_factors_batch

print(f"lunus {version('lunus')} OK")
print(f"  structure_factors_batch <- {structure_factors_batch.__module__}")
print(f"  mean_and_diffuse        <- {mean_and_diffuse.__module__}")
PY
