#!/usr/bin/env bash
# Install lunus.sf -- differentiable structure factors and diffuse scattering --
# into the active environment, from its own repository.
#
# lunus is developed at github.com/lanl/lunus, and is deliberately not vendored
# into this repo nor synced to pods (see .actlignore).
#
# You do NOT normally need this script. lunus IS declared in pyproject.toml and
# resolved in pixi.lock, so every pixi environment already has it at the pinned
# rev. This is for the one case the lock cannot cover: testing a lunus commit
# NEWER than the pin without regenerating the lock.
#
# That matters because the lock can only be regenerated by the Relock workflow,
# never locally -- `pixi lock` is all-or-nothing, with no --environment or
# --platform selector, and solving linux-64 needs a linux-64 prefix. So the edit
# -> test loop on lunus itself would otherwise cost a CI round trip per commit.
#
# Publishing lunus as a wheel would retire this script: the rev pin becomes an
# ordinary version specifier and bumps stop being SHA edits.
#
# Usage (from the repo root, inside the environment you want it in):
#   pixi run -e boltz bash scripts/install_lunus.sh              # reinstall the pin
#   LUNUS_REF=sf pixi run -e boltz bash scripts/install_lunus.sh # branch tip
set -euo pipefail

LUNUS_REPO="${LUNUS_REPO:-https://github.com/lanl/lunus.git}"
# Defaults to the rev pinned in pyproject.toml, so an unqualified run reproduces
# the locked environment rather than silently diverging from it. Keep the two in
# sync; pass LUNUS_REF to deliberately install something else.
LUNUS_REF="${LUNUS_REF:-fb22633f3279baf3e97f207d0bea4ce34733e6f8}"

echo "Installing lunus[sf] from ${LUNUS_REPO}@${LUNUS_REF}"

# The `sf` extra requires torch and gemmi. Both are already supplied by the pixi
# environment, and lunus leaves them unpinned, so pip treats them as satisfied
# and will not pull a second copy of torch over the conda-provided one.
# --upgrade forces a re-fetch, so re-running picks up new commits on a branch ref.
python -m pip install --upgrade "lunus[sf] @ git+${LUNUS_REPO}@${LUNUS_REF}"

# Verify rather than trust the exit status. lunus.sf resolves its public API
# lazily (PEP 562), so `import lunus.sf` alone succeeds even when the torch-side
# modules are broken or absent -- name the symbols the diffuse reward needs.
python - <<'PY'
from importlib.metadata import version

from lunus.sf import mean_and_diffuse, structure_factors_batch

print(f"lunus {version('lunus')} OK")
print(f"  structure_factors_batch <- {structure_factors_batch.__module__}")
print(f"  mean_and_diffuse        <- {mean_and_diffuse.__module__}")
PY
